- id: copyright
  name: copyright
  description: ''
  entry: copyright-check
  language: python
- id: commit-message
  name: check commit message
  description: ''
  entry: commit-message-check
  language: python
  args:
    - '--multiline'
  stages:
    - commit-msg
